# Generated by Django 3.1.5 on 2021-01-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
